[build]
  command = "npm run build"
  functions = "functions"

 [[redirects]]
   from = "/chat"
     to = "/.netlify/functions/server/chat"

 [[redirects]]
    from = "/auth"
    to = "/.netlify/functions/server/auth"

 [[redirects]]
     from = "/users"
     to = "/.netlify/functions/server/users"

 [[redirects]]
      from = "/registration"
      to = "/.netlify/functions/server/registration"

 [[redirects]]
       from = "/settings"
       to = "/.netlify/functions/server/settings"